### ISSUE TITLE
Panic during comparison

### ISSUE THREAD

**Issue by jekirl** [paupino/rust-decimal#58]
The following test cases will fail with `Decimal Overflow` due to rescaling

```
    #[test]
    fn test_max_compares() {
        let x = "225.33543601344182".parse::<Decimal>().unwrap();
        let y = Decimal::max_value();
        assert!(x < y);
        assert!(y > x);
        assert!(y != x);

    }
    #[test]
    fn test_min_compares() {
        let x = "225.33543601344182".parse::<Decimal>().unwrap();
        let y = Decimal::min_value();
        assert!(x > y);
        assert!(y < x);
        assert!(y != x);
    }
```

**Comment by paupino** [comment]
Further info:

```
---- decimal::test::test_max_compares stdout ----
	thread 'decimal::test::test_max_compares' panicked at 'Decimal Overflow', src/decimal.rs:392:12
stack backtrace:
   0:        0x10ac84c73 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h77f333888e74def2
   1:        0x10ac86a0a - std::panicking::default_hook::{{closure}}::he7cfcf7125dff55f
   2:        0x10ac86508 - std::panicking::default_hook::h99f8c39c0e377395
   3:        0x10ac88cd2 - std::panicking::rust_panic_with_hook::he7ea255c9426c7e7
   4:        0x10abf19c6 - std::panicking::begin_panic::h59a0a52935dd2803
   5:        0x10ac111ac - rust_decimal::decimal::Decimal::from_bytes_le::he19537cb02f624cc
   6:        0x10ac107b4 - rust_decimal::decimal::Decimal::rescale::h076f32ccc7ca84f5
   7:        0x10ac152bc - <rust_decimal::decimal::Decimal as core::cmp::Ord>::cmp::ha17542b8d9316ade
   8:        0x10ac1521c - <rust_decimal::decimal::Decimal as core::cmp::PartialOrd>::partial_cmp::h3b55f911c92beda5
   9:        0x10ac0162c - core::cmp::PartialOrd::lt::h14522f0ce10a6b85
  10:        0x10ac16871 - rust_decimal::decimal::test::test_max_compares::h80205b5e3f8fcb85
  11:        0x10ac53ab1 - <F as test::FnBox<T>>::call_box::h7d01a5d4825fcd4d
  12:        0x10ac89e2c - __rust_maybe_catch_panic
  13:        0x10ac44a58 - std::sys_common::backtrace::__rust_begin_short_backtrace::h00ee79cb1cc21f6e
  14:        0x10ac45827 - std::panicking::try::do_call::ha9fae25707519121
  15:        0x10ac89e2c - __rust_maybe_catch_panic
  16:        0x10ac4d733 - <F as alloc::boxed::FnBox<A>>::call_box::hc43bdbb6dd582cb8
  17:        0x10ac85fab - std::sys::imp::thread::Thread::new::thread_start::h48c72bb09587cbc3
  18:     0x7fff774556c0 - _pthread_body
  19:     0x7fff7745556c - _pthread_start

---- decimal::test::test_min_compares stdout ----
	thread 'decimal::test::test_min_compares' panicked at 'Decimal Overflow', src/decimal.rs:392:12
stack backtrace:
   0:        0x10ac84c73 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h77f333888e74def2
   1:        0x10ac86a0a - std::panicking::default_hook::{{closure}}::he7cfcf7125dff55f
   2:        0x10ac86508 - std::panicking::default_hook::h99f8c39c0e377395
   3:        0x10ac88cd2 - std::panicking::rust_panic_with_hook::he7ea255c9426c7e7
   4:        0x10abf19c6 - std::panicking::begin_panic::h59a0a52935dd2803
   5:        0x10ac111ac - rust_decimal::decimal::Decimal::from_bytes_le::he19537cb02f624cc
   6:        0x10ac107b4 - rust_decimal::decimal::Decimal::rescale::h076f32ccc7ca84f5
   7:        0x10ac152bc - <rust_decimal::decimal::Decimal as core::cmp::Ord>::cmp::ha17542b8d9316ade
   8:        0x10ac1521c - <rust_decimal::decimal::Decimal as core::cmp::PartialOrd>::partial_cmp::h3b55f911c92beda5
   9:        0x10ac0154c - core::cmp::PartialOrd::gt::h0536292073878af5
  10:        0x10ac16961 - rust_decimal::decimal::test::test_min_compares::hdc00d20cd24ca293
  11:        0x10ac53ab1 - <F as test::FnBox<T>>::call_box::h7d01a5d4825fcd4d
  12:        0x10ac89e2c - __rust_maybe_catch_panic
  13:        0x10ac44a58 - std::sys_common::backtrace::__rust_begin_short_backtrace::h00ee79cb1cc21f6e
  14:        0x10ac45827 - std::panicking::try::do_call::ha9fae25707519121
  15:        0x10ac89e2c - __rust_maybe_catch_panic
  16:        0x10ac4d733 - <F as alloc::boxed::FnBox<A>>::call_box::hc43bdbb6dd582cb8
  17:        0x10ac85fab - std::sys::imp::thread::Thread::new::thread_start::h48c72bb09587cbc3
  18:     0x7fff774556c0 - _pthread_body
  19:     0x7fff7745556c - _pthread_start
```

**Comment by paupino** [comment]
Long story short, this is due to rescaling requiring more significant digits than can be "technically" stored in the Decimal number formally (i.e. > 96 bits required). 

In this particular case `rescale` is only required temporarily so could be optimized to avoid panic since it's throwaway.
